import type { WorkflowNodeData } from "@/lib/flow/types"

export type WorkflowLanguage = "zh-CN" | "en-US"

export type LocalizedNodeText = {
  label: string
  description?: string
}

const NODE_TEXT: Record<string, Record<WorkflowLanguage, LocalizedNodeText>> = {
  "intelligence.input.collection-need": {
    "zh-CN": { label: "采集需求", description: "输入业务需求，由 demand-draft 组装真实 OpenCLI/source 节点" },
    "en-US": { label: "Collection Need", description: "Enter a collection need and assemble real OpenCLI/source nodes" },
  },
  "intelligence.schedule.cron": {
    "zh-CN": { label: "定时计划", description: "按 cron/interval 周期触发情报工作流" },
    "en-US": { label: "Cron Schedule", description: "Run the intelligence workflow on a cadence" },
  },
  "intelligence.source.jin10": {
    "zh-CN": { label: "金十快讯源", description: "读取金十快讯 fixture/live feed" },
    "en-US": { label: "JIN10 Source", description: "Read JIN10 flash news from fixture or live feed" },
  },
  "intelligence.source.opencli-slot": {
    "zh-CN": { label: "OpenCLI 来源槽", description: "由 HDA/source planner 生成并交给 OpenCLI channel 执行的来源槽" },
    "en-US": { label: "OpenCLI Source Slot", description: "Source slot generated by the HDA/source planner and executed through OpenCLI" },
  },
  "intelligence.source.pool": {
    "zh-CN": { label: "来源池", description: "把采集需求并行分发到真实 OpenCLI 来源槽" },
    "en-US": { label: "Source Pool", description: "Fan out collection demand to real OpenCLI source slots" },
  },
  "intelligence.processing.normalize": {
    "zh-CN": { label: "标准化条目", description: "统一字段、语言和时间格式" },
    "en-US": { label: "Normalize Items", description: "Normalize fields, language, and timestamps" },
  },
  "intelligence.processing.dedupe": {
    "zh-CN": { label: "去重条目", description: "按标题、时间和来源去重" },
    "en-US": { label: "Dedupe Items", description: "Deduplicate by title, time, and source" },
  },
  "intelligence.agent.summary": {
    "zh-CN": { label: "LLM 摘要", description: "生成短摘要和影响解释" },
    "en-US": { label: "LLM Summary", description: "Generate short summaries with impact notes" },
  },
  "intelligence.agent.score": {
    "zh-CN": { label: "重要性评分", description: "按影响范围和紧急度打分" },
    "en-US": { label: "Importance Score", description: "Score by market scope and urgency" },
  },
  "intelligence.agent.tag": {
    "zh-CN": { label: "自动标签", description: "给条目打主题、市场和风险标签" },
    "en-US": { label: "Auto Tag", description: "Tag items by topic, market, and risk" },
  },
  "intelligence.router.importance": {
    "zh-CN": { label: "重要性路由", description: "按分数和条件路由到 Inbox/Notify" },
    "en-US": { label: "Importance Router", description: "Route scored items to Inbox or Notify" },
  },
  "intelligence.output.inbox": {
    "zh-CN": { label: "复核收件箱", description: "保存到人工复核队列" },
    "en-US": { label: "Inbox Store", description: "Store items in the human review queue" },
  },
  "intelligence.output.collection-result": {
    "zh-CN": { label: "采集输出", description: "输出 OpenCLI HDA 标准化后的采集条目" },
    "en-US": { label: "Collection Output", description: "Expose normalized OpenCLI HDA collection items" },
  },
  "intelligence.output.webhook": {
    "zh-CN": { label: "Webhook 通知", description: "模拟 webhook 推送，真实通知后置" },
    "en-US": { label: "Webhook Notify", description: "Simulate webhook delivery before live sends" },
  },
  "intelligence.output.turbopush-publish": {
    "zh-CN": { label: "TurboPush 发布", description: "通过本机 TurboPush 服务发布到已登录平台账号" },
    "en-US": { label: "TurboPush Publish", description: "Publish through the local TurboPush service and logged accounts" },
  },
  "package.intelligence.pipeline": {
    "zh-CN": { label: "情报流水线", description: "封装定时抓取、标准化、摘要评分、复核和通知的情报流水线" },
    "en-US": { label: "Intelligence Pipeline", description: "Package source, normalize, summary, scoring, review, and delivery" },
  },
  "package.opencli.multi-source-hda": {
    "zh-CN": { label: "OpenCLI 多源 HDA", description: "封装可扩展 OpenCLI 来源槽并行 fanout 和内部标准化" },
    "en-US": { label: "OpenCLI Multi-source HDA", description: "Package extensible OpenCLI source-slot fanout and internal normalization" },
  },
  "package.ops.event": {
    "zh-CN": { label: "Ops 任务事件", description: "封装触发、队列、重试、日志和执行证据的任务事件" },
    "en-US": { label: "Ops Event", description: "Package trigger, queue, retry, log, and execution evidence" },
  },
  "package.ops.monitor-guard": {
    "zh-CN": { label: "监控闸门", description: "封装指标采集、阈值、delta 和限流的监控闸门" },
    "en-US": { label: "Monitor Guard", description: "Package metrics, thresholds, deltas, and rate guards" },
  },
  "package.ops.alert-response": {
    "zh-CN": { label: "告警响应", description: "封装告警分派、通知、工单、快照和升级动作" },
    "en-US": { label: "Alert Response", description: "Package alert dispatch, notification, ticket, snapshot, and escalation" },
  },
  "package.ai.prompt-experiment": {
    "zh-CN": { label: "Prompt 实验", description: "封装 prompt 版本、测试用例、模型对比和实验记录" },
    "en-US": { label: "Prompt Experiment", description: "Package prompt versions, test cases, model comparison, and experiment runs" },
  },
  "package.verify.regression-gate": {
    "zh-CN": { label: "回归门禁包", description: "封装 dataset、evaluator、scorecard 和回归门禁" },
    "en-US": { label: "Regression Gate", description: "Package datasets, evaluators, scorecards, and regression gates" },
  },
  "package.map.knowledge-map": {
    "zh-CN": { label: "知识图包", description: "封装来源锚点、语义连线、主题折叠和知识导出" },
    "en-US": { label: "Knowledge Map", description: "Package source anchors, semantic links, topic collapse, and knowledge export" },
  },
  "package.review.human-review": {
    "zh-CN": { label: "人工复核包", description: "封装人工审核、Inbox、审批分支和审计证据" },
    "en-US": { label: "Human Review", description: "Package human approval, inbox, approval branches, and audit evidence" },
  },
  "primitive.input.adapter-read": {
    "zh-CN": { label: "读取 Adapter", description: "从 adapter 或 fixture 读入原始 payload" },
    "en-US": { label: "Adapter Read", description: "Read raw payloads from an adapter or fixture" },
  },
  "primitive.transform.parse-json": {
    "zh-CN": { label: "解析 JSON", description: "解析 JSON/HTTP payload 为结构化对象" },
    "en-US": { label: "Parse JSON", description: "Parse a JSON or HTTP payload into an object" },
  },
  "primitive.transform.map-fields": {
    "zh-CN": { label: "字段映射", description: "字段映射、重命名、补默认值" },
    "en-US": { label: "Map Fields", description: "Map, rename, and default fields" },
  },
  "primitive.transform.filter-items": {
    "zh-CN": { label: "过滤条目", description: "按表达式过滤集合元素" },
    "en-US": { label: "Filter Items", description: "Filter item collections by expression" },
  },
  "primitive.ai.model-call": {
    "zh-CN": { label: "模型调用", description: "调用或模拟一个模型推理步骤" },
    "en-US": { label: "Model Call", description: "Run or simulate a model inference step" },
  },
  "primitive.ai.prompt-version": {
    "zh-CN": { label: "Prompt 版本", description: "保存 prompt 版本、备注和回滚锚点" },
    "en-US": { label: "Prompt Version", description: "Save prompt versions, notes, and rollback anchors" },
  },
  "primitive.ai.prompt-test-case": {
    "zh-CN": { label: "Prompt 测试用例", description: "给 prompt 绑定测试输入和期望输出" },
    "en-US": { label: "Prompt Test Case", description: "Bind prompt inputs and expected outputs" },
  },
  "primitive.ai.model-compare": {
    "zh-CN": { label: "模型对比", description: "并排比较多个模型或 mock 输出" },
    "en-US": { label: "Model Compare", description: "Compare model or mock outputs side by side" },
  },
  "primitive.ai.score-dimensions": {
    "zh-CN": { label: "维度打分", description: "按多个维度计算 importance score" },
    "en-US": { label: "Score Dimensions", description: "Score items across several importance dimensions" },
  },
  "primitive.logic.condition": {
    "zh-CN": { label: "条件闸门", description: "计算布尔条件并输出 true/false 分支" },
    "en-US": { label: "Condition Gate", description: "Evaluate a boolean condition and split branches" },
  },
  "primitive.state.inbox-write": {
    "zh-CN": { label: "写入 Inbox", description: "写入人工复核队列" },
    "en-US": { label: "Inbox Write", description: "Write items into the review queue" },
  },
  "primitive.output.mock-send": {
    "zh-CN": { label: "模拟发送", description: "模拟外部发送，保留 delivery 证据" },
    "en-US": { label: "Mock Send", description: "Simulate external delivery and keep evidence" },
  },
  "primitive.verify.assert-schema": {
    "zh-CN": { label: "Schema 断言", description: "断言输出满足 schema/contract" },
    "en-US": { label: "Assert Schema", description: "Assert that output matches a schema or contract" },
  },
  "primitive.verify.coverage-mark": {
    "zh-CN": { label: "覆盖率标记", description: "标记节点、事件或端口覆盖率" },
    "en-US": { label: "Coverage Mark", description: "Mark node, event, or port coverage" },
  },
  "primitive.verify.trace-span": {
    "zh-CN": { label: "Trace Span", description: "记录 prompt/model/tool 的 span 级观测信息" },
    "en-US": { label: "Trace Span", description: "Record span-level prompt, model, and tool evidence" },
  },
  "primitive.verify.eval-dataset": {
    "zh-CN": { label: "评测数据集", description: "声明评测数据集和 case 数" },
    "en-US": { label: "Eval Dataset", description: "Declare the evaluation dataset and case count" },
  },
  "primitive.verify.evaluator": {
    "zh-CN": { label: "评测器", description: "执行 accuracy/relevance/compliance 等评测器" },
    "en-US": { label: "Evaluator", description: "Run accuracy, relevance, compliance, and latency evaluators" },
  },
  "primitive.verify.experiment-run": {
    "zh-CN": { label: "实验运行", description: "记录一次 prompt/model 实验运行" },
    "en-US": { label: "Experiment Run", description: "Record one prompt or model experiment run" },
  },
  "primitive.verify.scorecard": {
    "zh-CN": { label: "评分卡", description: "汇总评测分数和质量门禁" },
    "en-US": { label: "Scorecard", description: "Summarize evaluation scores and quality gates" },
  },
  "primitive.verify.regression-gate": {
    "zh-CN": { label: "回归门禁", description: "检测 prompt/model 改动是否退化" },
    "en-US": { label: "Regression Gate", description: "Detect regressions from prompt or model changes" },
  },
  "primitive.business.source-health": {
    "zh-CN": { label: "数据源健康", description: "检查数据源延迟、空结果和错误率" },
    "en-US": { label: "Source Health", description: "Check source latency, empty results, and error rate" },
  },
  "primitive.business.freshness-gate": {
    "zh-CN": { label: "时效闸门", description: "按发布时间和抓取时间过滤过期情报" },
    "en-US": { label: "Freshness Gate", description: "Filter stale intelligence by publish and fetch time" },
  },
  "primitive.business.entity-extract": {
    "zh-CN": { label: "实体提取", description: "提取公司、国家、品种、人物等实体" },
    "en-US": { label: "Entity Extract", description: "Extract companies, countries, instruments, and people" },
  },
  "primitive.business.topic-classify": {
    "zh-CN": { label: "主题分类", description: "把情报归入宏观、外汇、商品、政策、风险主题" },
    "en-US": { label: "Topic Classify", description: "Classify items into macro, FX, commodity, policy, and risk topics" },
  },
  "primitive.business.sentiment-score": {
    "zh-CN": { label: "情绪评分", description: "计算利多/利空/中性和置信度" },
    "en-US": { label: "Sentiment Score", description: "Score bullish, bearish, neutral signals" },
  },
  "primitive.business.impact-estimate": {
    "zh-CN": { label: "影响估计", description: "估计事件影响范围、市场关联和紧急度" },
    "en-US": { label: "Impact Estimate", description: "Estimate scope, market linkage, and urgency" },
  },
  "primitive.business.evidence-pack": {
    "zh-CN": { label: "证据包", description: "把来源、原文、摘要、评分组装成可审计证据包" },
    "en-US": { label: "Evidence Pack", description: "Bundle source, raw text, summary, and score for audit" },
  },
  "primitive.business.digest-compose": {
    "zh-CN": { label: "简报组装", description: "把多条情报整理成一条人工可读简报" },
    "en-US": { label: "Digest Compose", description: "Compose several intelligence items into a readable brief" },
  },
  "primitive.business.human-approval": {
    "zh-CN": { label: "人工审核", description: "需要人工确认后才允许进入发送或写入动作" },
    "en-US": { label: "Human Approval", description: "Require operator approval before send or write actions" },
  },
  "primitive.business.delivery-rate-limit": {
    "zh-CN": { label: "发送限流", description: "控制通知频率，避免重复轰炸" },
    "en-US": { label: "Rate Limit", description: "Limit delivery frequency to prevent repeated notifications" },
  },
  "primitive.ops.trigger-manual": {
    "zh-CN": { label: "手动触发", description: "允许用户或 API 手动启动任务" },
    "en-US": { label: "Manual Trigger", description: "Allow users or APIs to manually launch jobs" },
  },
  "primitive.ops.trigger-schedule": {
    "zh-CN": { label: "计划触发", description: "按 cron/日历规则触发任务" },
    "en-US": { label: "Schedule Trigger", description: "Launch jobs from cron or calendar rules" },
  },
  "primitive.ops.trigger-interval": {
    "zh-CN": { label: "间隔触发", description: "按固定秒级间隔触发任务" },
    "en-US": { label: "Interval Trigger", description: "Launch jobs on a fixed interval" },
  },
  "primitive.ops.trigger-single-shot": {
    "zh-CN": { label: "单次触发", description: "在指定时间点只触发一次" },
    "en-US": { label: "Single Shot Trigger", description: "Launch once at a specified time" },
  },
  "primitive.ops.trigger-webhook": {
    "zh-CN": { label: "入站 Webhook", description: "通过带 token 的入站 webhook 启动任务" },
    "en-US": { label: "Webhook Trigger", description: "Launch jobs from a tokenized inbound webhook" },
  },
  "primitive.ops.trigger-startup": {
    "zh-CN": { label: "启动触发", description: "服务启动后触发初始化任务" },
    "en-US": { label: "Startup Trigger", description: "Launch initialization jobs after service startup" },
  },
  "primitive.ops.trigger-catch-up": {
    "zh-CN": { label: "补跑游标", description: "补跑暂停或停机期间错过的计划任务" },
    "en-US": { label: "Catch-Up Cursor", description: "Replay scheduled jobs missed during downtime" },
  },
  "primitive.ops.trigger-range": {
    "zh-CN": { label: "允许时间窗", description: "只允许任务在指定时间窗内启动" },
    "en-US": { label: "Range Window", description: "Allow launches only inside a time window" },
  },
  "primitive.ops.trigger-blackout": {
    "zh-CN": { label: "禁用时间窗", description: "阻止维护窗口或假期期间的自动启动" },
    "en-US": { label: "Blackout Window", description: "Block launches during maintenance or holidays" },
  },
  "primitive.ops.trigger-delay": {
    "zh-CN": { label: "延迟启动", description: "给计划启动增加延迟" },
    "en-US": { label: "Delay Start", description: "Add a delay to scheduled launches" },
  },
  "primitive.ops.trigger-precision": {
    "zh-CN": { label: "秒级启动", description: "在分钟内按指定秒偏移启动" },
    "en-US": { label: "Precision Start", description: "Launch at specific second offsets inside a minute" },
  },
  "primitive.ops.limit-runtime": {
    "zh-CN": { label: "运行超时限制", description: "限制任务最大运行时间并产出超时证据" },
    "en-US": { label: "Runtime Limit", description: "Limit max runtime and emit timeout evidence" },
  },
  "primitive.ops.limit-concurrency": {
    "zh-CN": { label: "并发限制", description: "限制同一事件或 workflow 的并发任务数" },
    "en-US": { label: "Concurrency Limit", description: "Limit concurrent jobs for an event or workflow" },
  },
  "primitive.ops.limit-output-size": {
    "zh-CN": { label: "输出大小限制", description: "限制日志或输出字节数" },
    "en-US": { label: "Output Size Limit", description: "Limit log or output byte size" },
  },
  "primitive.ops.limit-memory": {
    "zh-CN": { label: "内存限制", description: "检测持续超出内存阈值的任务" },
    "en-US": { label: "Memory Limit", description: "Detect sustained memory limit violations" },
  },
  "primitive.ops.limit-cpu": {
    "zh-CN": { label: "CPU 限制", description: "检测持续超出 CPU 阈值的任务" },
    "en-US": { label: "CPU Limit", description: "Detect sustained CPU limit violations" },
  },
  "primitive.ops.limit-retry": {
    "zh-CN": { label: "重试策略", description: "为失败任务配置最大重试次数和退避间隔" },
    "en-US": { label: "Retry Policy", description: "Configure max retries and retry delay" },
  },
  "primitive.ops.limit-queue": {
    "zh-CN": { label: "队列限制", description: "限制排队任务数量并决定是否拒绝" },
    "en-US": { label: "Queue Limit", description: "Limit queued jobs and decide rejection" },
  },
  "primitive.ops.limit-file": {
    "zh-CN": { label: "文件限制", description: "限制输入文件数量、大小和扩展名" },
    "en-US": { label: "File Limit", description: "Limit input file count, size, and extensions" },
  },
  "primitive.ops.limit-daily": {
    "zh-CN": { label: "每日限制", description: "限制每天某类结果或通知次数" },
    "en-US": { label: "Daily Limit", description: "Limit daily result or notification counts" },
  },
  "primitive.ops.action-email": {
    "zh-CN": { label: "邮件动作", description: "发送邮件通知并保留投递结果" },
    "en-US": { label: "Email Action", description: "Send email and keep delivery evidence" },
  },
  "primitive.ops.action-webhook": {
    "zh-CN": { label: "Webhook 动作", description: "向外部系统发送 HTTP webhook" },
    "en-US": { label: "Webhook Action", description: "Send an HTTP webhook to an external system" },
  },
  "primitive.ops.action-run-event": {
    "zh-CN": { label: "运行事件", description: "从告警或节点结果启动另一个事件" },
    "en-US": { label: "Run Event Action", description: "Launch another event from an alert or node result" },
  },
  "primitive.ops.action-channel": {
    "zh-CN": { label: "通知通道", description: "通过通知 channel 执行邮件、webhook 或 UI 通知" },
    "en-US": { label: "Channel Action", description: "Notify through an email, webhook, or UI channel" },
  },
  "primitive.ops.action-snapshot": {
    "zh-CN": { label: "服务器快照", description: "采集服务器进程、负载和网络快照" },
    "en-US": { label: "Snapshot Action", description: "Capture server process, load, and network snapshots" },
  },
  "primitive.ops.action-ticket": {
    "zh-CN": { label: "工单动作", description: "创建或更新 incident ticket" },
    "en-US": { label: "Ticket Action", description: "Create or update an incident ticket" },
  },
  "primitive.ops.action-plugin": {
    "zh-CN": { label: "插件动作", description: "调用动作插件并记录插件输出" },
    "en-US": { label: "Plugin Action", description: "Run an action plugin and record plugin output" },
  },
  "primitive.ops.action-suspend-job": {
    "zh-CN": { label: "暂停任务", description: "暂停正在运行或排队的任务" },
    "en-US": { label: "Suspend Job", description: "Suspend a running or queued job" },
  },
  "primitive.ops.action-disable-event": {
    "zh-CN": { label: "禁用事件", description: "禁用触发源或事件定义" },
    "en-US": { label: "Disable Event", description: "Disable a trigger source or event definition" },
  },
  "primitive.ops.action-bucket-store": {
    "zh-CN": { label: "写入 Bucket", description: "把运行数据或文件写入 bucket" },
    "en-US": { label: "Bucket Store", description: "Store run data or files in a bucket" },
  },
  "primitive.ops.action-bucket-fetch": {
    "zh-CN": { label: "读取 Bucket", description: "从 bucket 读取运行数据或文件" },
    "en-US": { label: "Bucket Fetch", description: "Fetch run data or files from a bucket" },
  },
  "primitive.ops.action-apply-tags": {
    "zh-CN": { label: "应用标签", description: "给任务、告警或工单打标签" },
    "en-US": { label: "Apply Tags", description: "Apply tags to jobs, alerts, or tickets" },
  },
  "primitive.ops.monitor-metric-expression": {
    "zh-CN": { label: "指标表达式", description: "从实时监控数据中提取数值指标" },
    "en-US": { label: "Metric Expression", description: "Extract numeric metrics from live monitor data" },
  },
  "primitive.ops.monitor-data-match": {
    "zh-CN": { label: "数据匹配", description: "用正则从文本监控输出中抽取数值" },
    "en-US": { label: "Data Match", description: "Extract numeric values from text monitor output" },
  },
  "primitive.ops.monitor-delta": {
    "zh-CN": { label: "差分监控", description: "计算指标变化率或差分" },
    "en-US": { label: "Delta Monitor", description: "Compute metric deltas or rates" },
  },
  "primitive.ops.monitor-quick": {
    "zh-CN": { label: "快速监控", description: "秒级轻量监控采样，用于短期趋势" },
    "en-US": { label: "Quick Monitor", description: "Second-level sampling for short-term trend lines" },
  },
  "primitive.ops.plugin-shell": {
    "zh-CN": { label: "Shell 插件", description: "以受控插件形式执行 shell 脚本" },
    "en-US": { label: "Shell Plugin", description: "Run shell scripts through a controlled plugin boundary" },
  },
  "primitive.ops.plugin-http-request": {
    "zh-CN": { label: "HTTP 请求插件", description: "发送 HTTP 请求并保留响应证据" },
    "en-US": { label: "HTTP Request Plugin", description: "Send HTTP requests and keep response evidence" },
  },
  "primitive.ops.plugin-docker": {
    "zh-CN": { label: "Docker 插件", description: "在容器边界内运行脚本或工具" },
    "en-US": { label: "Docker Plugin", description: "Run scripts or tools inside a container boundary" },
  },
  "primitive.ops.plugin-test-fixture": {
    "zh-CN": { label: "测试样本插件", description: "产生样本数据或样本文件用于测试 workflow" },
    "en-US": { label: "Test Fixture Plugin", description: "Emit sample data or files for workflow tests" },
  },
  "primitive.ops.secret-ref": {
    "zh-CN": { label: "密钥引用", description: "声明运行时注入的 secret 引用而不暴露明文" },
    "en-US": { label: "Secret Ref", description: "Declare runtime secret references without exposing values" },
  },
  "primitive.core.manual-trigger": {
    "zh-CN": { label: "手动触发", description: "手动启动一次 workflow 调试运行" },
    "en-US": { label: "Manual Trigger", description: "Manually start one workflow test run" },
  },
  "primitive.core.schedule-trigger": {
    "zh-CN": { label: "日程触发", description: "按 n8n 风格日程启动 workflow" },
    "en-US": { label: "Schedule Trigger", description: "Start a workflow on a schedule" },
  },
  "primitive.core.webhook-trigger": {
    "zh-CN": { label: "Webhook 触发", description: "接收入站 HTTP 请求并启动 workflow" },
    "en-US": { label: "Webhook Trigger", description: "Receive inbound HTTP requests and start a workflow" },
  },
  "primitive.core.error-trigger": {
    "zh-CN": { label: "错误触发", description: "在 workflow 失败时启动错误处理链路" },
    "en-US": { label: "Error Trigger", description: "Start an error handling flow when a workflow fails" },
  },
  "primitive.core.edit-fields": {
    "zh-CN": { label: "编辑字段", description: "设置、重命名、保留或移除 item 字段" },
    "en-US": { label: "Edit Fields", description: "Set, rename, keep, or remove item fields" },
  },
  "primitive.core.code": {
    "zh-CN": { label: "代码节点", description: "用 JavaScript/Python 风格脚本处理 items" },
    "en-US": { label: "Code", description: "Process items with JavaScript or Python style code" },
  },
  "primitive.core.http-request": {
    "zh-CN": { label: "HTTP 请求", description: "发送 HTTP/API 请求并返回响应" },
    "en-US": { label: "HTTP Request", description: "Send HTTP or API requests and return responses" },
  },
  "primitive.core.respond-webhook": {
    "zh-CN": { label: "响应 Webhook", description: "把 workflow 结果作为 webhook 响应返回" },
    "en-US": { label: "Respond to Webhook", description: "Return workflow results as the webhook response" },
  },
  "primitive.core.if": {
    "zh-CN": { label: "IF 条件", description: "按条件把 items 分成 true/false 分支" },
    "en-US": { label: "IF", description: "Split items into true and false branches" },
  },
  "primitive.core.switch": {
    "zh-CN": { label: "Switch 分支", description: "按表达式把 items 路由到多个分支" },
    "en-US": { label: "Switch", description: "Route items to multiple branches by expression" },
  },
  "primitive.core.merge": {
    "zh-CN": { label: "合并", description: "合并两个输入流，可 append/combine/wait" },
    "en-US": { label: "Merge", description: "Merge two input streams using append, combine, or wait modes" },
  },
  "primitive.core.loop-over-items": {
    "zh-CN": { label: "循环 Items", description: "按 batch size 循环处理 items" },
    "en-US": { label: "Loop Over Items", description: "Process items in batches" },
  },
  "primitive.core.wait": {
    "zh-CN": { label: "等待", description: "暂停执行直到时间、条件或 webhook 恢复" },
    "en-US": { label: "Wait", description: "Pause execution until time, condition, or webhook resume" },
  },
  "primitive.core.execute-workflow": {
    "zh-CN": { label: "执行 Workflow", description: "调用另一个 workflow 并传递输入 items" },
    "en-US": { label: "Execute Workflow", description: "Call another workflow with input items" },
  },
  "primitive.core.stop-and-error": {
    "zh-CN": { label: "停止并报错", description: "主动终止 workflow 并产出错误证据" },
    "en-US": { label: "Stop and Error", description: "Stop a workflow and emit error evidence" },
  },
  "primitive.core.filter": {
    "zh-CN": { label: "过滤", description: "保留满足条件的 items" },
    "en-US": { label: "Filter", description: "Keep items matching conditions" },
  },
  "primitive.core.remove-duplicates": {
    "zh-CN": { label: "移除重复", description: "按字段或全部内容去重 items" },
    "en-US": { label: "Remove Duplicates", description: "Deduplicate items by fields or full content" },
  },
  "primitive.core.sort": {
    "zh-CN": { label: "排序", description: "按字段或表达式排序 items" },
    "en-US": { label: "Sort", description: "Sort items by fields or expressions" },
  },
  "primitive.core.limit": {
    "zh-CN": { label: "数量限制", description: "限制通过的 item 数量" },
    "en-US": { label: "Limit", description: "Limit the number of items passing through" },
  },
  "primitive.core.aggregate": {
    "zh-CN": { label: "聚合", description: "把多个 items 聚合成统计或数组" },
    "en-US": { label: "Aggregate", description: "Aggregate items into stats or arrays" },
  },
  "primitive.core.split-out": {
    "zh-CN": { label: "拆出数组", description: "把数组字段拆成多条 items" },
    "en-US": { label: "Split Out", description: "Split array fields into multiple items" },
  },
  "primitive.core.date-time": {
    "zh-CN": { label: "日期时间", description: "格式化、偏移或解析日期时间字段" },
    "en-US": { label: "Date & Time", description: "Format, offset, or parse date-time fields" },
  },
  "primitive.core.no-op": {
    "zh-CN": { label: "空操作", description: "占位、连接或调试用的空操作节点" },
    "en-US": { label: "No Operation", description: "Passthrough node for placeholders or debugging" },
  },
  "primitive.map.source-anchor": {
    "zh-CN": { label: "来源锚点", description: "给节点绑定可回跳的来源定位信息" },
    "en-US": { label: "Source Anchor", description: "Bind nodes to jumpable source location data" },
  },
  "primitive.map.jump-back": {
    "zh-CN": { label: "回跳来源", description: "从图节点跳回原始消息、网页或证据位置" },
    "en-US": { label: "Jump Back", description: "Jump from graph nodes back to original messages, pages, or evidence" },
  },
  "primitive.map.mini-map": {
    "zh-CN": { label: "节点小图", description: "把一个长节点展开成内部小图" },
    "en-US": { label: "Mini Map", description: "Expand one long node into an embedded mini map" },
  },
  "primitive.map.topic-collapse": {
    "zh-CN": { label: "主题折叠", description: "把多个相关节点折叠成可恢复主题组" },
    "en-US": { label: "Topic Collapse", description: "Collapse related nodes into a restorable topic group" },
  },
  "primitive.map.semantic-link": {
    "zh-CN": { label: "语义连线", description: "建立带类型、理由和置信度的语义连线" },
    "en-US": { label: "Semantic Link", description: "Create typed relationship links with reasons and confidence" },
  },
  "primitive.map.link-weight": {
    "zh-CN": { label: "连线权重", description: "给关系连线设置权重、重要性和显示强度" },
    "en-US": { label: "Link Weight", description: "Set relationship weight, importance, and visual strength" },
  },
  "primitive.map.knowledge-export": {
    "zh-CN": { label: "知识图导出", description: "导出 Canvas、OPML、Markdown、SVG 或 PNG 知识图" },
    "en-US": { label: "Knowledge Export", description: "Export Canvas, OPML, Markdown, SVG, or PNG knowledge maps" },
  },
}

const COLLECTION_NEED_CATALOG_ID = "intelligence.input.collection-need"

type CanonicalNodeData = {
  catalogId?: string
  kind?: string
  capability?: string
  adapter?: string
  params?: Record<string, unknown>
}

export function getNodeDisplayId(data: WorkflowNodeData): string | undefined {
  if (data.externalWorkflow?.source) return undefined
  if (typeof data.primitiveId === "string") return data.primitiveId
  if (isCollectionNeedData(data)) return COLLECTION_NEED_CATALOG_ID
  const canonical = readCanonicalNodeData(data)
  if (canonical?.catalogId) return canonical.catalogId

  const kind = canonical?.kind
  const capability = canonical?.capability
  const params = canonical?.params ?? {}
  if (kind === "schedule") return "intelligence.schedule.cron"
  if (kind === "source" && typeof canonical?.adapter === "string" && canonical.adapter.startsWith("opencli-")) return "intelligence.source.opencli-slot"
  if (kind === "source") return "intelligence.source.jin10"
  if (kind === "router") return "intelligence.router.importance"
  if (kind === "inbox" && params.queue === "opencli-hda-output") return "intelligence.output.collection-result"
  if (kind === "inbox") return "intelligence.output.inbox"
  if (kind === "notify" && typeof canonical?.adapter === "string" && canonical.adapter.startsWith("turbopush")) return "intelligence.output.turbopush-publish"
  if (kind === "notify") return "intelligence.output.webhook"
  if (kind === "agent" && capability === "normalize" && params.fanout === "parallel") return "intelligence.source.pool"
  if (kind === "agent" && capability === "normalize") return "intelligence.processing.normalize"
  if (kind === "agent" && capability === "dedupe") return "intelligence.processing.dedupe"
  if (kind === "agent" && capability === "summarize") return "intelligence.agent.summary"
  if (kind === "agent" && capability === "score") return "intelligence.agent.score"
  if (kind === "agent" && capability === "tag") return "intelligence.agent.tag"

  return undefined
}

function isCollectionNeedData(data: WorkflowNodeData): boolean {
  const canonical = readCanonicalNodeData(data)
  if (canonical?.catalogId === COLLECTION_NEED_CATALOG_ID) return true
  if (canonical?.kind !== "schedule" || canonical.capability !== "trigger") return false
  if (canonical.params?.mode === "demand-draft") return true
  return hasNeedShape(canonical?.params) && !hasScheduleShape(canonical?.params)
}

function readCanonicalNodeData(data: WorkflowNodeData): CanonicalNodeData | undefined {
  const canonical = data.canonical
  if (!canonical || typeof canonical !== "object" || Array.isArray(canonical)) return undefined
  return canonical as CanonicalNodeData
}

function hasNeedShape(params: Record<string, unknown> | undefined): boolean {
  return typeof params?.text === "string" || typeof params?.locale === "string"
}

function hasScheduleShape(params: Record<string, unknown> | undefined): boolean {
  return typeof params?.interval === "string" || typeof params?.timezone === "string"
}

export function localizeNodeText(id: string | undefined, fallback: LocalizedNodeText, language: WorkflowLanguage): LocalizedNodeText {
  if (!id) return fallback
  return NODE_TEXT[id]?.[language] ?? fallback
}
