import type { WorkflowNodeData } from "@/lib/flow/types"
import { getNodeDisplayId } from "./node-i18n"

export type NodeVisualPattern = "solid" | "split" | "dots" | "gate" | "pulse"

export type NodeVisualSignature = {
  code: string
  glyph: string
  stripe: string
  pattern: NodeVisualPattern
}

const VISUALS: Record<string, NodeVisualSignature> = {
  "intelligence.schedule.cron": sig("CLK", "T", "var(--chart-1)", "pulse"),
  "intelligence.source.jin10": sig("J10", "S", "var(--chart-4)", "dots"),
  "intelligence.processing.normalize": sig("NRM", "N", "var(--chart-2)", "split"),
  "intelligence.processing.dedupe": sig("DED", "D", "var(--chart-2)", "gate"),
  "intelligence.agent.summary": sig("SUM", "A", "var(--chart-2)", "solid"),
  "intelligence.agent.score": sig("SCR", "#", "var(--chart-3)", "pulse"),
  "intelligence.agent.tag": sig("TAG", "+", "var(--chart-3)", "dots"),
  "intelligence.router.importance": sig("RTE", "Y", "var(--chart-5)", "gate"),
  "intelligence.output.inbox": sig("INB", "I", "var(--chart-4)", "split"),
  "intelligence.output.webhook": sig("WHK", "!", "var(--chart-1)", "pulse"),
  "package.intelligence.pipeline": sig("PKI", "P", "var(--chart-2)", "solid"),
  "package.ops.event": sig("OPS", "O", "var(--chart-4)", "solid"),
  "package.ops.monitor-guard": sig("MON", "M", "var(--chart-4)", "gate"),
  "package.ops.alert-response": sig("ALT", "!", "var(--chart-1)", "pulse"),
  "package.ai.prompt-experiment": sig("PEX", "P", "var(--state-action)", "split"),
  "package.verify.regression-gate": sig("REG", "G", "#4ade80", "gate"),
  "package.map.knowledge-map": sig("KMP", "K", "var(--chart-3)", "split"),
  "package.review.human-review": sig("REV", "R", "var(--chart-4)", "gate"),
  "primitive.input.adapter-read": sig("ADR", "S", "var(--state-data)", "dots"),
  "primitive.input.manual-sample": sig("SMP", "M", "var(--state-data)", "solid"),
  "primitive.transform.parse-json": sig("JSN", "{ }", "var(--chart-2)", "split"),
  "primitive.transform.map-fields": sig("MAP", "->", "var(--chart-2)", "split"),
  "primitive.transform.filter-items": sig("FLT", "F", "var(--chart-2)", "gate"),
  "primitive.transform.limit-window": sig("LMT", "H", "var(--chart-2)", "gate"),
  "primitive.ai.prompt-template": sig("PRM", "P", "var(--state-action)", "solid"),
  "primitive.ai.prompt-version": sig("PVR", "V", "var(--state-action)", "split"),
  "primitive.ai.prompt-test-case": sig("PTC", "T", "var(--state-action)", "dots"),
  "primitive.ai.model-call": sig("LLM", "A", "var(--state-action)", "pulse"),
  "primitive.ai.model-compare": sig("CMP", "=", "var(--state-action)", "split"),
  "primitive.ai.score-dimensions": sig("DIM", "#", "var(--chart-3)", "pulse"),
  "primitive.logic.condition": sig("IF", "Y", "var(--chart-5)", "gate"),
  "primitive.logic.branch-label": sig("BRN", "Y", "var(--chart-5)", "split"),
  "primitive.state.cache-window": sig("CAC", "C", "var(--state-data)", "dots"),
  "primitive.state.inbox-write": sig("INW", "I", "var(--state-data)", "split"),
  "primitive.output.payload-format": sig("FMT", "P", "var(--state-action)", "split"),
  "primitive.output.mock-send": sig("SND", "!", "var(--state-action)", "pulse"),
  "primitive.verify.assert-schema": sig("AST", "V", "#4ade80", "gate"),
  "primitive.verify.coverage-mark": sig("COV", "%", "#4ade80", "dots"),
  "primitive.verify.trace-span": sig("SPN", "S", "#4ade80", "pulse"),
  "primitive.verify.eval-dataset": sig("EDS", "D", "#4ade80", "dots"),
  "primitive.verify.evaluator": sig("EVL", "E", "#4ade80", "gate"),
  "primitive.verify.experiment-run": sig("EXP", "X", "#4ade80", "pulse"),
  "primitive.verify.scorecard": sig("SCD", "#", "#4ade80", "split"),
  "primitive.verify.regression-gate": sig("REG", "G", "#4ade80", "gate"),
  "primitive.business.source-health": sig("HLT", "H", "var(--chart-4)", "pulse"),
  "primitive.business.freshness-gate": sig("FRS", "T", "var(--chart-1)", "gate"),
  "primitive.business.entity-extract": sig("ENT", "E", "var(--chart-2)", "dots"),
  "primitive.business.topic-classify": sig("TOP", "T", "var(--chart-3)", "dots"),
  "primitive.business.sentiment-score": sig("SNT", "+-", "var(--chart-3)", "pulse"),
  "primitive.business.impact-estimate": sig("IMP", "!", "var(--chart-5)", "pulse"),
  "primitive.business.evidence-pack": sig("EVD", "E", "#4ade80", "split"),
  "primitive.business.digest-compose": sig("DIG", "D", "var(--state-action)", "solid"),
  "primitive.business.human-approval": sig("APR", "A", "#4ade80", "gate"),
  "primitive.business.delivery-rate-limit": sig("RAT", "H", "var(--chart-1)", "gate"),
  "primitive.ops.trigger-manual": sig("MAN", "M", "var(--chart-1)", "pulse"),
  "primitive.ops.trigger-schedule": sig("SCH", "T", "var(--chart-1)", "pulse"),
  "primitive.ops.trigger-interval": sig("INT", "R", "var(--chart-1)", "pulse"),
  "primitive.ops.trigger-single-shot": sig("ONE", "1", "var(--chart-1)", "solid"),
  "primitive.ops.trigger-webhook": sig("IWH", "W", "var(--chart-4)", "dots"),
  "primitive.ops.trigger-startup": sig("SUP", "Z", "var(--chart-1)", "pulse"),
  "primitive.ops.trigger-catch-up": sig("CUR", "C", "var(--chart-2)", "split"),
  "primitive.ops.trigger-range": sig("RNG", "[]", "var(--chart-5)", "gate"),
  "primitive.ops.trigger-blackout": sig("BLK", "X", "var(--chart-5)", "gate"),
  "primitive.ops.trigger-delay": sig("DLY", "H", "var(--chart-1)", "split"),
  "primitive.ops.trigger-precision": sig("PRC", "s", "var(--chart-1)", "dots"),
  "primitive.ops.limit-runtime": sig("TMO", "H", "var(--chart-5)", "gate"),
  "primitive.ops.limit-concurrency": sig("CON", "||", "var(--chart-5)", "gate"),
  "primitive.ops.limit-output-size": sig("LOG", "L", "var(--chart-5)", "gate"),
  "primitive.ops.limit-memory": sig("MEM", "M", "var(--chart-5)", "gate"),
  "primitive.ops.limit-cpu": sig("CPU", "%", "var(--chart-5)", "gate"),
  "primitive.ops.limit-retry": sig("RTY", "R", "var(--chart-5)", "split"),
  "primitive.ops.limit-queue": sig("QUE", "Q", "var(--chart-5)", "gate"),
  "primitive.ops.limit-file": sig("FIL", "F", "var(--chart-5)", "gate"),
  "primitive.ops.limit-daily": sig("DAY", "D", "var(--chart-5)", "gate"),
  "primitive.ops.action-email": sig("EML", "@", "var(--state-action)", "pulse"),
  "primitive.ops.action-webhook": sig("WHK", "W", "var(--state-action)", "pulse"),
  "primitive.ops.action-run-event": sig("RUN", ">", "var(--state-action)", "solid"),
  "primitive.ops.action-channel": sig("CHN", "C", "var(--state-action)", "dots"),
  "primitive.ops.action-snapshot": sig("SNP", "S", "var(--state-data)", "split"),
  "primitive.ops.action-ticket": sig("TKT", "!", "var(--state-action)", "split"),
  "primitive.ops.action-plugin": sig("PLG", "P", "var(--state-action)", "solid"),
  "primitive.ops.action-suspend-job": sig("SUS", "P", "var(--chart-5)", "gate"),
  "primitive.ops.action-disable-event": sig("OFF", "0", "var(--chart-5)", "gate"),
  "primitive.ops.action-bucket-store": sig("BST", "B", "var(--state-data)", "split"),
  "primitive.ops.action-bucket-fetch": sig("BFH", "B", "var(--state-data)", "dots"),
  "primitive.ops.action-apply-tags": sig("TAG", "+", "var(--chart-3)", "dots"),
  "primitive.ops.monitor-metric-expression": sig("MET", "M", "var(--chart-4)", "pulse"),
  "primitive.ops.monitor-data-match": sig("MTX", "R", "var(--chart-4)", "split"),
  "primitive.ops.monitor-delta": sig("DLT", "d", "var(--chart-4)", "pulse"),
  "primitive.ops.monitor-quick": sig("QMN", "Q", "var(--chart-4)", "pulse"),
  "primitive.ops.plugin-shell": sig("SHL", "$", "var(--state-action)", "solid"),
  "primitive.ops.plugin-http-request": sig("REQ", "H", "var(--state-action)", "pulse"),
  "primitive.ops.plugin-docker": sig("DKR", "D", "var(--state-action)", "split"),
  "primitive.ops.plugin-test-fixture": sig("FIX", "F", "var(--state-data)", "dots"),
  "primitive.ops.secret-ref": sig("SEC", "K", "#4ade80", "gate"),
  "primitive.core.manual-trigger": sig("MAN", "M", "var(--chart-1)", "pulse"),
  "primitive.core.schedule-trigger": sig("SCH", "T", "var(--chart-1)", "pulse"),
  "primitive.core.webhook-trigger": sig("WEB", "W", "var(--chart-4)", "dots"),
  "primitive.core.error-trigger": sig("ERR", "!", "var(--chart-5)", "pulse"),
  "primitive.core.edit-fields": sig("SET", "=", "var(--chart-2)", "split"),
  "primitive.core.code": sig("COD", "{ }", "var(--chart-2)", "solid"),
  "primitive.core.http-request": sig("HTTP", "H", "var(--state-action)", "pulse"),
  "primitive.core.respond-webhook": sig("RSP", "<", "var(--state-action)", "solid"),
  "primitive.core.if": sig("IF", "Y", "var(--chart-5)", "gate"),
  "primitive.core.switch": sig("SWT", "Y", "var(--chart-5)", "gate"),
  "primitive.core.merge": sig("MRG", "+", "var(--chart-2)", "split"),
  "primitive.core.loop-over-items": sig("LOP", "R", "var(--chart-2)", "pulse"),
  "primitive.core.wait": sig("WAI", "H", "var(--chart-1)", "split"),
  "primitive.core.execute-workflow": sig("EXE", ">", "var(--state-action)", "solid"),
  "primitive.core.stop-and-error": sig("STP", "X", "var(--chart-5)", "gate"),
  "primitive.core.filter": sig("FLT", "F", "var(--chart-2)", "gate"),
  "primitive.core.remove-duplicates": sig("DED", "D", "var(--chart-2)", "gate"),
  "primitive.core.sort": sig("SRT", "S", "var(--chart-2)", "split"),
  "primitive.core.limit": sig("LIM", "L", "var(--chart-2)", "gate"),
  "primitive.core.aggregate": sig("AGG", "#", "var(--chart-2)", "split"),
  "primitive.core.split-out": sig("SPL", "S", "var(--chart-2)", "split"),
  "primitive.core.date-time": sig("DAT", "T", "var(--chart-1)", "dots"),
  "primitive.core.no-op": sig("NOP", "N", "var(--muted-foreground)", "solid"),
  "primitive.map.source-anchor": sig("SRC", "S", "var(--chart-4)", "dots"),
  "primitive.map.jump-back": sig("JMP", "J", "var(--chart-4)", "pulse"),
  "primitive.map.mini-map": sig("MIN", "M", "var(--chart-3)", "split"),
  "primitive.map.topic-collapse": sig("TPC", "G", "var(--chart-3)", "gate"),
  "primitive.map.semantic-link": sig("SEM", "~", "var(--chart-2)", "split"),
  "primitive.map.link-weight": sig("WGT", "%", "var(--chart-5)", "pulse"),
  "primitive.map.knowledge-export": sig("EXP", "E", "#4ade80", "solid"),
}

const CATEGORY_VISUALS: Record<string, NodeVisualSignature> = {
  trigger: sig("TRG", "T", "var(--chart-1)", "pulse"),
  action: sig("ACT", "A", "var(--state-action)", "solid"),
  logic: sig("LOG", "Y", "var(--chart-5)", "gate"),
  data: sig("DAT", "D", "var(--state-data)", "dots"),
  annotation: sig("TXT", "N", "var(--muted-foreground)", "split"),
  shape: sig("SHP", "S", "var(--border)", "solid"),
}

export function getNodeVisualSignature(data: WorkflowNodeData): NodeVisualSignature {
  const displayId = getNodeDisplayId(data)
  if (displayId && VISUALS[displayId]) return VISUALS[displayId]
  const primitiveCategory = typeof data.primitiveCategory === "string" ? data.primitiveCategory : undefined
  if (primitiveCategory && CATEGORY_VISUALS[primitiveCategory]) return CATEGORY_VISUALS[primitiveCategory]
  return CATEGORY_VISUALS[data.category] ?? sig("NOD", "N", "var(--border)", "solid")
}

function sig(code: string, glyph: string, stripe: string, pattern: NodeVisualPattern): NodeVisualSignature {
  return { code, glyph, stripe, pattern }
}
