import type { FlowState } from "@/lib/flow/store"

export function selectEditorCanvasState(state: FlowState) {
  return {
    addNodeFromPalette: state.addNodeFromPalette,
    addPrimitiveNode: state.addPrimitiveNode,
    addWorkflowNodeFromCatalog: state.addWorkflowNodeFromCatalog,
    applyWorkflowCapabilities: state.applyWorkflowCapabilities,
    attachToParent: state.attachToParent,
    autoLayout: state.autoLayout,
    clearHelperLines: state.clearHelperLines,
    clearPendingAgentProposal: state.clearPendingAgentProposal,
    clearProposalFocus: state.clearProposalFocus,
    copy: state.copy,
    cut: state.cut,
    deleteSelected: state.deleteSelected,
    detachFromParent: state.detachFromParent,
    disconnectNodeConnections: state.disconnectNodeConnections,
    duplicate: state.duplicateSelected,
    edges: state.edges,
    enterNodeNetwork: state.enterNodeNetwork,
    exitNodeNetwork: state.exitNodeNetwork,
    focusProposalTargets: state.focusProposalTargets,
    groupSelection: state.groupSelection,
    helperLines: state.helperLines,
    importWorkflowProject: state.importWorkflowProject,
    lockNodeInternals: state.lockNodeInternals,
    networkStack: state.networkStack,
    nodes: state.nodes,
    onConnect: state.onConnect,
    onEdgesChange: state.onEdgesChange,
    onNodesChange: state.onNodesChange,
    paste: state.paste,
    pendingAgentProposal: state.pendingAgentProposal,
    redo: state.redo,
    removeEdgesByIds: state.removeEdgesByIds,
    resizeGroupToFit: state.resizeGroupToFit,
    resolveNodeCollisions: state.resolveNodeCollisions,
    save: state.save,
    selectConnectedComponent: state.selectConnectedComponent,
    setToolMode: state.setToolMode,
    takeSnapshot: state.takeSnapshot,
    toolMode: state.toolMode,
    undo: state.undo,
    unlockNodeInternals: state.unlockNodeInternals,
    updateWorkflowProfile: state.updateWorkflowProfile,
    workflowProject: state.workflowProject,
  }
}
