import type { PaletteItem } from "./types"

export const NODE_PALETTE: PaletteItem[] = [
  /* ---------------- triggers ---------------- */
  {
    nodeType: "trigger",
    category: "trigger",
    label: "Webhook 触发",
    description: "接收外部 HTTP 回调启动工作流",
    icon: "Zap",
    color: "var(--chart-1)",
    defaultData: { fields: [{ id: "path", label: "路径", value: "/hooks/order" }] },
  },
  {
    nodeType: "trigger",
    category: "trigger",
    label: "定时触发",
    description: "按 Cron 表达式周期启动",
    icon: "Clock",
    color: "var(--chart-1)",
    defaultData: { fields: [{ id: "cron", label: "Cron", value: "0 9 * * 1-5" }] },
  },
  {
    nodeType: "trigger",
    category: "trigger",
    label: "手动触发",
    description: "由用户手动点击启动",
    icon: "Play",
    color: "var(--chart-1)",
  },
  {
    nodeType: "trigger",
    category: "trigger",
    label: "事件订阅",
    description: "监听消息队列 / 事件总线",
    icon: "Radio",
    color: "var(--chart-1)",
    defaultData: { fields: [{ id: "topic", label: "主题", value: "order.created" }] },
  },

  /* ---------------- actions ---------------- */
  {
    nodeType: "http",
    category: "action",
    label: "HTTP 请求",
    description: "调用外部 API 接口",
    icon: "Globe",
    color: "var(--chart-2)",
    defaultData: {
      fields: [
        { id: "method", label: "方法", value: "POST" },
        { id: "url", label: "地址", value: "https://api.example.com" },
      ],
    },
  },
  {
    nodeType: "action",
    category: "action",
    label: "发送邮件",
    description: "向指定收件人发送邮件",
    icon: "Mail",
    color: "var(--chart-2)",
    defaultData: {
      fields: [
        { id: "to", label: "收件人", value: "{{user.email}}" },
        { id: "template", label: "模板", value: "welcome" },
      ],
    },
  },
  {
    nodeType: "action",
    category: "action",
    label: "发送消息",
    description: "推送 IM / Slack / 钉钉消息",
    icon: "MessageSquare",
    color: "var(--chart-2)",
    defaultData: { fields: [{ id: "channel", label: "频道", value: "#ops" }] },
  },
  {
    nodeType: "action",
    category: "action",
    label: "数据库写入",
    description: "插入或更新数据库记录",
    icon: "Database",
    color: "var(--chart-2)",
    defaultData: {
      fields: [
        { id: "table", label: "表", value: "orders" },
        { id: "op", label: "操作", value: "upsert" },
      ],
    },
  },
  {
    nodeType: "action",
    category: "action",
    label: "推送通知",
    description: "发送 App / Web 推送通知",
    icon: "Bell",
    color: "var(--chart-2)",
    defaultData: { fields: [{ id: "title", label: "标题", value: "订单已发货" }] },
  },
  {
    nodeType: "action",
    category: "action",
    label: "AI 生成",
    description: "调用 LLM 生成文本 / 决策",
    icon: "Sparkles",
    color: "var(--chart-2)",
    defaultData: {
      fields: [
        { id: "model", label: "模型", value: "gpt-4o-mini" },
        { id: "prompt", label: "提示词", value: "总结该工单内容" },
      ],
    },
  },

  /* ---------------- logic ---------------- */
  {
    nodeType: "condition",
    category: "logic",
    label: "条件分支",
    description: "按条件走向 true / false 分支",
    icon: "GitBranch",
    color: "var(--chart-3)",
    defaultData: { condition: "value > 0" },
  },
  {
    nodeType: "condition",
    category: "logic",
    label: "开关路由",
    description: "按字段值路由到多个分支",
    icon: "Split",
    color: "var(--chart-3)",
    defaultData: { condition: "order.type" },
  },
  {
    nodeType: "delay",
    category: "logic",
    label: "延时等待",
    description: "暂停一段时间后继续",
    icon: "Clock",
    color: "var(--chart-3)",
    defaultData: { fields: [{ id: "duration", label: "时长", value: "5m" }] },
  },
  {
    nodeType: "delay",
    category: "logic",
    label: "等待事件",
    description: "挂起直到外部事件到达",
    icon: "Hourglass",
    color: "var(--chart-3)",
    defaultData: { fields: [{ id: "event", label: "事件", value: "payment.confirmed" }] },
  },
  {
    nodeType: "transform",
    category: "logic",
    label: "合并分支",
    description: "等待多个上游分支全部完成",
    icon: "GitMerge",
    color: "var(--chart-3)",
    defaultData: { fields: [{ id: "mode", label: "模式", value: "waitAll" }] },
  },
  {
    nodeType: "transform",
    category: "logic",
    label: "循环执行",
    description: "对集合中的每一项执行子流程",
    icon: "Repeat",
    color: "var(--chart-3)",
    defaultData: { fields: [{ id: "items", label: "集合", value: "{{order.items}}" }] },
  },

  /* ---------------- data ---------------- */
  {
    nodeType: "transform",
    category: "data",
    label: "数据转换",
    description: "运行表达式处理数据",
    icon: "Code",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "expr", label: "表达式", value: "return input" }] },
  },
  {
    nodeType: "transform",
    category: "data",
    label: "字段映射",
    description: "重命名 / 挑选 / 组装字段",
    icon: "ArrowRightLeft",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "mapping", label: "映射", value: "id → orderId" }] },
  },
  {
    nodeType: "transform",
    category: "data",
    label: "过滤",
    description: "按条件过滤集合元素",
    icon: "Filter",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "predicate", label: "条件", value: "item.qty > 0" }] },
  },
  {
    nodeType: "transform",
    category: "data",
    label: "聚合统计",
    description: "count / sum / groupBy 聚合",
    icon: "Sigma",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "agg", label: "聚合", value: "sum(amount)" }] },
  },
  {
    nodeType: "transform",
    category: "data",
    label: "代码执行",
    description: "运行自定义 JavaScript",
    icon: "Terminal",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "code", label: "代码", value: "return { ...input }" }] },
  },
  {
    nodeType: "http",
    category: "data",
    label: "数据库查询",
    description: "执行 SQL 查询取数",
    icon: "Database",
    color: "var(--chart-4)",
    defaultData: { fields: [{ id: "sql", label: "SQL", value: "SELECT * FROM orders" }] },
  },

  /* ---------------- annotation ---------------- */
  {
    nodeType: "group",
    category: "annotation",
    label: "分组容器",
    description: "将多个节点组织在一起",
    icon: "Group",
    color: "var(--chart-5)",
    defaultData: { collapsed: false },
  },
  {
    nodeType: "note",
    category: "annotation",
    label: "备注",
    description: "添加说明文字",
    icon: "StickyNote",
    color: "var(--chart-5)",
    defaultData: { description: "在此输入备注内容..." },
  },

  /* ---------------- flowchart shapes ---------------- */
  { nodeType: "shape", category: "shape", label: "矩形", description: "流程步骤", icon: "Square", color: "var(--chart-2)", shape: "round" },
  { nodeType: "shape", category: "shape", label: "圆形", description: "起止节点", icon: "Circle", color: "var(--chart-1)", shape: "circle" },
  { nodeType: "shape", category: "shape", label: "菱形", description: "判定 / 决策", icon: "Diamond", color: "var(--chart-3)", shape: "diamond" },
  { nodeType: "shape", category: "shape", label: "六边形", description: "准备 / 预处理", icon: "Hexagon", color: "var(--chart-4)", shape: "hexagon" },
  { nodeType: "shape", category: "shape", label: "平行四边形", description: "输入 / 输出", icon: "Shapes", color: "var(--chart-2)", shape: "parallelogram" },
  { nodeType: "shape", category: "shape", label: "圆柱", description: "数据存储", icon: "Cylinder", color: "var(--chart-4)", shape: "cylinder" },
]

export const CATEGORY_LABELS: Record<string, string> = {
  trigger: "触发",
  action: "动作",
  logic: "逻辑",
  data: "数据",
  annotation: "标注",
  shape: "流程图形",
}
